Repository OutSystems/docs-product, pull requests merged in 2020-11, with the labels that each got.

#120 Ui patterns batch 13
  related.yml
  src/develop/ui/patterns/mobile/content/images/useravatar-1-ss.png
  src/develop/ui/patterns/mobile/content/images/useravatar-2-ss.png
  src/develop/ui/patterns/mobile/content/useravatar.md
  src/develop/ui/patterns/mobile/numbers/counter.md
  src/develop/ui/patterns/mobile/utilities/buttonloading.md
  src/develop/ui/patterns/mobile/utilities/centercontent.md
  src/develop/ui/patterns/mobile/utilities/images/buttonloading-2-ss.png
  src/develop/ui/patterns/mobile/utilities/images/buttonloading-3-ss.png
  src/develop/ui/patterns/mobile/utilities/images/buttonloading-4-ss.png
  src/develop/ui/patterns/mobile/utilities/images/buttonloading-5-ss.png
  src/develop/ui/patterns/mobile/utilities/images/buttonloading-6-ss.png
  src/develop/ui/patterns/mobile/utilities/images/centercontent-4-ss.png
  src/develop/ui/patterns/mobile/utilities/images/margincontainer-1-ss.png
  src/develop/ui/patterns/mobile/utilities/images/margincontainer-2-ss.png
  src/develop/ui/patterns/mobile/utilities/images/margincontainer-3-ss.png
  src/develop/ui/patterns/mobile/utilities/images/margincontainer-4-ss.png
  src/develop/ui/patterns/mobile/utilities/margincontainer.md
Labels: cla:yes, type/improvement

#121 Ui patterns batch 14
  src/develop/ui/patterns/mobile/interaction/floatingactions.md
  src/develop/ui/patterns/mobile/interaction/images/floatingactions-4-ss.png
  src/develop/ui/patterns/mobile/navigation/images/pagination-10-ss.png
  src/develop/ui/patterns/mobile/navigation/images/pagination-11-ss.png
  src/develop/ui/patterns/mobile/navigation/images/pagination-12-ss.png
  src/develop/ui/patterns/mobile/navigation/images/pagination-13-ss.png
  src/develop/ui/patterns/mobile/navigation/images/pagination-2-ss.png
  src/develop/ui/patterns/mobile/navigation/images/pagination-9-ss.png
  src/develop/ui/patterns/mobile/navigation/pagination.md
Labels: cla:yes, type/improvement

#114 Progressbar ui pattern
  src/develop/ui/patterns/mobile/numbers/images/progressbar-1-ss.png
  src/develop/ui/patterns/mobile/numbers/images/progressbar-10-ss.png
  src/develop/ui/patterns/mobile/numbers/images/progressbar-2-ss.png
  src/develop/ui/patterns/mobile/numbers/images/progressbar-3-ss.png
  src/develop/ui/patterns/mobile/numbers/images/progressbar-4-ss.png
  src/develop/ui/patterns/mobile/numbers/images/progressbar-5-ss.png
  src/develop/ui/patterns/mobile/numbers/images/progressbar-6-ss.png
  src/develop/ui/patterns/mobile/numbers/images/progressbar-7-ss.png
  src/develop/ui/patterns/mobile/numbers/images/progressbar-8-ss.png
  src/develop/ui/patterns/mobile/numbers/images/progressbar-9-ss.png
  src/develop/ui/patterns/mobile/numbers/progressbar.md
  toc.yml
Labels: cla:yes, type/new_content

#110 Update platformruntime-api.md
  src/ref/apis/auto/platformruntime-api.md
Labels: cla:yes, type/improvement

#122 Pagination ui pattern
  src/develop/ui/patterns/mobile/navigation/images/pagination-14-ss.png
  src/develop/ui/patterns/mobile/navigation/pagination.md
Labels: cla:yes, type/improvement

#79 Inform users when a light BPT exec is possible
  src/develop/processes/light-process.md
Labels: cla:yes, type/improvement

#88 Update customize-rest-urls.md
  related.yml
  src/extensibility-and-integration/rest/expose-rest-apis/customize-rest-urls.md
Labels: cla:yes, type/improvement

#97 #RTAF-3434 - Update version where issue for App Feedback in Reactive will be fixed
  src/managing-the-applications-lifecycle/app-feedback/user-feedback-enable.md
Labels: cla:yes, status/waiting_for_release, type/improvement

#58 #RRCT-2985 Added missing documentation
  src/ref/apis/performancemonitoring-api.md
Labels: status/waiting_for_release, type/new_content

#123 Update known issue
  src/deliver-mobile/distribute-pwa/intro.md
Labels: cla:yes

#125 Minor typo fix
  src/develop/ui/accessibility/intro.md
Labels: cla:yes

#126 Is it left uncaught or is caught to trigger the rollback?
  src/ref/data/database/handling-transactions.md
  src/ref/lang/auto/Class.Exception Handler.begin.md
Labels: cla:yes, type/improvement

#81 Update site.md
  src/develop/data/site.md
Labels: cla:yes, type/improvement

#129 Update Class.For Each.md
  src/ref/lang/auto/Class.For Each.md
Labels: cla:yes

#131 Update documentation to state that integrated authentication is available only in Traditional Web
  src/develop/security/end-user-manage/end-user-authentication/configure-active-directory.md
  src/develop/security/end-user-manage/end-user-authentication/integrated-authentication.md
Labels: cla:yes

#133 Ui patterns batch 16
  related.yml
  src/develop/ui/patterns/mobile/content/chatmessage.md
  src/develop/ui/patterns/mobile/content/images/chatmessage-3.png
  src/develop/ui/patterns/mobile/content/images/chatmessage-4-ss.png
  src/develop/ui/patterns/mobile/content/images/chatmessage-5-ss.png
  src/develop/ui/patterns/mobile/interaction/actionsheet.md
  src/develop/ui/patterns/mobile/interaction/images/actionsheet-1-ss.png
  src/develop/ui/patterns/mobile/interaction/images/actionsheet-2-ss.png
  src/develop/ui/patterns/mobile/interaction/images/actionsheet-3-ss.png
  src/develop/ui/patterns/mobile/interaction/images/actionsheet-4-ss.png
  src/develop/ui/patterns/mobile/interaction/images/actionsheet-5-ss.png
  src/develop/ui/patterns/mobile/interaction/images/actionsheet-6-ss.png
  src/develop/ui/patterns/mobile/interaction/images/actionsheet-7-ss.png
  src/develop/ui/patterns/mobile/interaction/images/actionsheet-8-ss.png
  src/develop/ui/patterns/mobile/interaction/images/actionsheet-9-ss.png
  src/develop/ui/patterns/mobile/interaction/images/video-2-ss.png
  src/develop/ui/patterns/mobile/interaction/images/video-3-ss.png
  src/develop/ui/patterns/mobile/interaction/images/video-4-ss.png
  src/develop/ui/patterns/mobile/interaction/images/video-5-ss.png
  src/develop/ui/patterns/mobile/interaction/images/video-6-ss.png
  src/develop/ui/patterns/mobile/interaction/images/video-7-ss.png
  src/develop/ui/patterns/mobile/interaction/images/video-8-ss.png
  src/develop/ui/patterns/mobile/interaction/images/video-9-ss.png
  src/develop/ui/patterns/mobile/interaction/video.md
  src/develop/ui/patterns/mobile/numbers/progressbar.md
  src/develop/ui/patterns/mobile/utilities/images/mouseevents-1-ss.png
  src/develop/ui/patterns/mobile/utilities/images/mouseevents-10-ss.png
  src/develop/ui/patterns/mobile/utilities/images/mouseevents-11-ss.png
  src/develop/ui/patterns/mobile/utilities/images/mouseevents-2-ss.png
  src/develop/ui/patterns/mobile/utilities/images/mouseevents-3-ss.png
  src/develop/ui/patterns/mobile/utilities/images/mouseevents-4-ss.png
  src/develop/ui/patterns/mobile/utilities/images/mouseevents-5-ss.png
  src/develop/ui/patterns/mobile/utilities/images/mouseevents-6-ss.png
  src/develop/ui/patterns/mobile/utilities/images/mouseevents-7-ss.png
  src/develop/ui/patterns/mobile/utilities/images/mouseevents-8-ss.png
  src/develop/ui/patterns/mobile/utilities/images/mouseevents-9-ss.png
  src/develop/ui/patterns/mobile/utilities/images/touchevents-7-ss.gif
  src/develop/ui/patterns/mobile/utilities/mouseevents.md
  toc.yml
Labels: cla:yes

#128 Sentence typo
  src/develop/ui/forms/form-validate.md
Labels: cla:yes

#134 Update intro.md
  src/develop/ui/screen-templates-create/intro.md
Labels: cla:yes
