Repository OutSystems/docs-product, pull requests merged in 2020-02, with the labels that each got.

#1 Add link to further reference
  src/develop/ui/multilingual/translations-editor.md
Labels: type/enhancement

#2 Add Master Class to Multilingual UI intro
  src/develop/ui/multilingual/intro.md
Labels: status/waiting_review, type/enhancement

#4 Changes to OutSystems UI intro page
  src/develop/ui/intro.md
Labels: status/waiting_review, type/enhancement

#6 typo fixed
  src/managing-the-applications-lifecycle/deploy-applications/plan-a-deployment-for-the-operations-team.md
Labels: status/waiting_review, type/fix

#7 Convert to SQL
  src/develop/data/query/images/convert-to-sql.gif
  src/develop/data/query/sql.md
Labels: type/enhancement
