Repository OutSystems/docs-product, pull requests merged in 2020-12, with the labels that each got.

#132 RRCT-3142 Mobile Sessions behavior on log out
  src/managing-the-applications-lifecycle/secure-the-applications/configure-authentication.md
Labels: cla:no, cla:yes

#135 Clarify doubts regarding "Timeout in Seconds"
  src/managing-the-applications-lifecycle/monitor-and-troubleshoot/logging/reference.md
  src/ref/lang/auto/ServiceStudio.Plugin.REST.RestAction.md
  src/ref/lang/auto/ServiceStudio.Plugin.SOAP.SOAPAction.md
Labels: cla:yes, type/improvement

#136 Maps ui pattern
  src/develop/ui/patterns/mobile/interaction/images/map-1-ss.png
  src/develop/ui/patterns/mobile/interaction/images/map-2-ss.png
  src/develop/ui/patterns/mobile/interaction/images/map-3-ss.png
  src/develop/ui/patterns/mobile/interaction/map.md
  toc.yml
Labels: cla:yes, type/new_content

#137 RRCT-3296 TextToDecimal and TextToInteger funtions throw exceptions in aggregates
  src/ref/lang/auto/builtinfunction.Data Conversion.md
Labels: cla:no, cla:yes, type/improvement

#138 RRCT-3296 TextToLongInteger funtion throw exceptions in aggregates
  src/ref/lang/auto/builtinfunction.Data Conversion.md
Labels: cla:yes, type/improvement

#130 Add limitation on email links generation
  src/managing-the-applications-lifecycle/deploy-applications/zones/intro.md
Labels: cla:no, cla:yes, type/improvement

#127 Added logging view period
  src/managing-the-applications-lifecycle/monitor-and-troubleshoot/monitoring-an-environment.md
Labels: cla:yes, type/improvement

#139 Q4 wizard web
  src/develop/ui/patterns/web/navigation/wizard.md
Labels: cla:yes, type/fix

#140 Update mobile-app-update-scenarios.md
  src/deliver-mobile/mobile-app-update-scenarios.md
Labels: cla:no, cla:yes

#141 Small grammer adjustments
  src/develop/processes/light-process.md
Labels: cla:yes
