Repository OutSystems/docs-product, pull requests merged in 2020-08, with the labels that each got.

#71 Update intro.md
  src/deliver-mobile/generate-and-distribute-your-mobile-app/generate-and-distribute-your-mobile-app-for-development-tests.md
  src/deliver-mobile/preview-your-mobile-app-in-the-device-using-outsystems-now.md
  src/develop/troubleshoot/advanced-mobile-app-troubleshooting-using-chrome.md
  src/develop/troubleshoot/debug/intro.md
  src/develop/troubleshoot/debug/troubleshoot-debugger-connection.md
  src/extensibility-and-integration/mobile-plugins/intro.md
  src/getting-started/create-mobile.md
  src/setup/unattended-install/intro.md
  toc.yml
Labels: type/correction

#59 Update sample-data.md
  src/develop/ui/screen-templates-create/images/manage-dependencies-sample-data-module-ss.png
  src/develop/ui/screen-templates-create/images/manage-dependencies-ss.png
  src/develop/ui/screen-templates-create/images/sample-data-export-ss.png
  src/develop/ui/screen-templates-create/sample-data.md
Labels: status/waiting_for_internal_info, type/improvement

#68 Fixed article's switched around descriptions for Development and Ad-hoc iOS configurations
  src/deliver-mobile/generate-and-distribute-your-mobile-app/publish-your-mobile-ios-application-to-the-apple-app-store.md
Labels: type/improvement

#46 Delete 'data type' duplicated words
  src/develop/data/structure-create-use.md
Labels: type/fix

#51 Add troubleshooting section
  src/ref/errors-and-warnings/errors/concurrent-publishing-error.md
Labels: type/improvement

#66 Update database-indexes.md
  src/ref/data/database/database-indexes.md
Labels: status/waiting_for_internal_info, type/fix, type/improvement

#83 Removed the references for Sample Screens
  related.yml
  src/develop/ui/patterns/mobile/adaptive/columns.md
  src/develop/ui/patterns/web/layout/images/layoutpopup-1-ss.png
  src/develop/ui/patterns/web/layout/images/loginform-1-ss.png
  src/develop/ui/patterns/web/layout/images/loginform-3-ss.png
  src/develop/ui/patterns/web/layout/layout-popup.md
  src/develop/ui/patterns/web/layout/loginform.md
  src/ref/ui-patterns/web/images/layout-popup-1-diag.png
  src/ref/ui-patterns/web/images/layout-popup-2-ss.png
  src/ref/ui-patterns/web/images/loginform-1-diag.png
  src/ref/ui-patterns/web/images/loginform-2-ss.png
  src/ref/ui-patterns/web/images/loginform-4-ss.png
  src/ref/ui-patterns/web/layout-popup.md
  src/ref/ui-patterns/web/loginform.md
  toc.yml
Labels: cla:yes
