Repository OutSystems/docs-product, pull requests merged in 2020-03, with the labels that each got.

#8 Update plan-a-deployment-for-the-operations-team.md
  src/managing-the-applications-lifecycle/deploy-applications/plan-a-deployment-for-the-operations-team.md
Labels: status/feedback_wanted, type/enhancement

#5 Update documentation for deployment zones limitations
  src/managing-the-applications-lifecycle/deploy-applications/zones/intro.md
Labels: status/waiting_review, type/correction

#11 Update Output Structure section description
  src/develop/data/query/sql.md
Labels: status/waiting_review

#15 Clarify CC and BCC emails
  src/extensibility-and-integration/configure-send-emails.md
Labels: type/enhancement

#19 Fix image file extensions lower case
  src/extensibility-and-integration/artificial-intelligence/images/chatbot-web-image14.png
  src/extensibility-and-integration/artificial-intelligence/images/chatbot-web-image15.png
  src/extensibility-and-integration/artificial-intelligence/images/chatbot-web-image16.png
Labels: type/fix
