Repository OutSystems/docs-product, pull requests merged in 2020-10, with the labels that each got.

#103 Number of Timers running in parallel
  src/develop/timers/intro.md
Labels: cla:no, cla:yes

#87 Update invalid-url-path-error.md
  src/ref/errors-and-warnings/errors/invalid-url-path-error.md
Labels: cla:yes, type/improvement

#106 Q3 editable table widget
  src/ref/lang/auto/ServiceStudio.Plugin.Widgets.EditableTable.begin.md
  src/ref/lang/auto/ServiceStudio.Plugin.Widgets.EditableTable.md
  src/ref/lang/auto/images/editabletable-1-ss.png
  src/ref/lang/auto/images/editabletable-2-ss.png
  src/ref/lang/auto/images/editabletable-3-ss.png
  src/ref/lang/auto/images/editabletable-4-ss.png
  src/ref/lang/auto/images/editabletable-5-ss.png
  src/ref/lang/auto/images/editabletable-6-ss.png
  src/ref/lang/auto/images/editabletable-7-ss.png
Labels: cla:yes

#107 Q3 button group
  related.yml
  src/ref/lang/auto/ServiceStudio.Plugin.NRWidgets.ButtonGroupItem.begin.md
  src/ref/lang/auto/ServiceStudio.Plugin.NRWidgets.ButtonGroupItem.md
  src/ref/lang/auto/images/buttongroupitem-1-ss.png
Labels: cla:yes

#105 Q3 class message
  src/ref/lang/auto/Class.Message.begin.md
  src/ref/lang/auto/Class.Message.md
  src/ref/lang/auto/images/message-class-1-ss.png
  src/ref/lang/auto/images/message-class-2-ss.png
  src/ref/lang/auto/images/message-class-3-ss.png
  src/ref/lang/auto/images/message-class-4-ss.png
  src/ref/lang/auto/images/message-class-5-ss.png
  src/ref/lang/auto/images/message-class-6-ss.png
Labels: cla:yes

#92 Corrected grammatical error in entity-property description-text.
  src/ref/lang/auto/Class.Entity.md
Labels: cla:yes, type/fix

#108 Q3 security warning
  src/ref/errors-and-warnings/warnings/images/security-warning-1-ss.png
  src/ref/errors-and-warnings/warnings/images/security-warning-2-ss.png
  src/ref/errors-and-warnings/warnings/security-warning.md
Labels: cla:yes, type/improvement

#109 Q3 invalid flow error
  src/ref/errors-and-warnings/errors/images/invalid-flow-error-1-ss.png
  src/ref/errors-and-warnings/errors/images/invalid-flow-error-2-ss.png
  src/ref/errors-and-warnings/errors/images/invalid-flow-error-3-ss.png
  src/ref/errors-and-warnings/errors/invalid-flow-error.md
Labels: cla:yes, type/improvement

#84 Update pagination-sorting.md
  src/develop/ui/table/pagination-sorting.md
Labels: cla:no, cla:yes, status/waiting_for_internal_info, type/improvement

#102 Update screen-update-list-items.md
  src/develop/logic/screen-update-list-items.md
Labels: cla:yes, type/fix

#104 Update available-data-types.md
  src/ref/data/data-types/available-data-types.md
Labels: cla:yes, type/fix

#96 #RTAF-3424 - Update PWA documentation regarding an issue found in PS 11.9.0
  src/deliver-mobile/distribute-pwa/intro.md
Labels: cla:no, cla:yes, type/improvement

#112 User avatar
  src/develop/ui/patterns/mobile/content/images/useravatar-1-ss.png
  src/develop/ui/patterns/mobile/content/images/useravatar-2-ss.png
  src/develop/ui/patterns/mobile/content/images/useravatar-9-ss.png
  src/develop/ui/patterns/mobile/content/useravatar.md
Labels: cla:yes, type/improvement

#117 Ui pattern section group
  related.yml
  src/develop/ui/patterns/mobile/content/carditem.md
  src/develop/ui/patterns/mobile/content/images/carditem-1.png
  src/develop/ui/patterns/mobile/content/images/carditem-2-ss.png
  src/develop/ui/patterns/mobile/content/images/carditem-3-ss.png
  src/develop/ui/patterns/mobile/content/images/carditem-4-ss.png
  src/develop/ui/patterns/mobile/content/images/sectiongroup-1-ss.png
  src/develop/ui/patterns/mobile/content/images/sectiongroup-2-ss.png
  src/develop/ui/patterns/mobile/content/images/sectiongroup-3-ss.png
  src/develop/ui/patterns/mobile/content/images/sectiongroup-4-ss.png
  src/develop/ui/patterns/mobile/content/images/sectiongroup-5-ss.png
  src/develop/ui/patterns/mobile/content/images/sectiongroup-6-ss.png
  src/develop/ui/patterns/mobile/content/sectiongroup.md
  toc.yml
Labels: cla:yes

#116 Content card item ui pattern
  related.yml
  src/develop/ui/patterns/mobile/content/carditem.md
Labels: cla:yes, type/improvement

#113 Dropdown ui pattern
  src/develop/ui/patterns/web/controls/dropdown.md
  src/develop/ui/patterns/web/controls/images/dropdown-1-ss.png
  src/develop/ui/patterns/web/controls/images/dropdown-10-ss.png
  src/develop/ui/patterns/web/controls/images/dropdown-11-ss.png
  src/develop/ui/patterns/web/controls/images/dropdown-12-ss.png
  src/develop/ui/patterns/web/controls/images/dropdown-13-ss.png
  src/develop/ui/patterns/web/controls/images/dropdown-14-ss.png
  src/develop/ui/patterns/web/controls/images/dropdown-15-ss.png
  src/develop/ui/patterns/web/controls/images/dropdown-19-ss.png
  src/develop/ui/patterns/web/controls/images/dropdown-2-ss.png
  src/develop/ui/patterns/web/controls/images/dropdown-20-ss.png
  src/develop/ui/patterns/web/controls/images/dropdown-21-ss.png
  src/develop/ui/patterns/web/controls/images/dropdown-22-ss.png
  src/develop/ui/patterns/web/controls/images/dropdown-3-ss.png
  src/develop/ui/patterns/web/controls/images/dropdown-4-ss.png
  src/develop/ui/patterns/web/controls/images/dropdown-5-ss.png
  src/develop/ui/patterns/web/controls/images/dropdown-6-ss.png
  src/develop/ui/patterns/web/controls/images/dropdown-7-ss.png
  src/develop/ui/patterns/web/controls/images/dropdown-8-ss.png
  src/develop/ui/patterns/web/controls/images/dropdown-9-ss.png
  src/develop/ui/patterns/web/controls/images/dropdown-image-3.png
  src/develop/ui/patterns/web/controls/images/dropdown-image-4.png
Labels: cla:yes, type/improvement

#111 Update Class.On Application Ready.md
  src/ref/lang/auto/Class.On Application Ready.md
Labels: cla:yes

#93 Corrected the description of the entity-property 'Label Attribute'.
  src/ref/lang/auto/Class.Entity.md
Labels: cla:yes, type/fix

#85 Update ml-connector.md
  src/extensibility-and-integration/artificial-intelligence/ml-connector.md
Labels: cla:yes, type/fix
