Repository OutSystems/docs-product, pull requests merged in 2020-09, with the labels that each got.

#89 Adding notice about upload widget limits
  src/ref/lang/auto/ServiceStudio.Plugin.NRWidgets.Upload.begin.md
Labels: cla:yes, type/improvement

#80 Update watches.md
  src/develop/troubleshoot/debug/watches.md
Labels: cla:no, cla:yes, type/improvement

#94 Update intro.md
  src/develop/application-templates/intro.md
Labels: cla:yes, type/improvement

#100 Doc improvements batch 1
  src/develop/ui/screen-templates-create/images/forge-1-ss.png
  src/develop/ui/screen-templates-create/images/forge-10-ss.png
  src/develop/ui/screen-templates-create/images/forge-11-ss.png
  src/develop/ui/screen-templates-create/images/forge-12-ss.png
  src/develop/ui/screen-templates-create/images/forge-13-ss.png
  src/develop/ui/screen-templates-create/images/forge-14-ss.png
  src/develop/ui/screen-templates-create/images/forge-2-ss.png
  src/develop/ui/screen-templates-create/images/forge-3-ss.png
  src/develop/ui/screen-templates-create/images/forge-4-ss.png
  src/develop/ui/screen-templates-create/images/forge-5-ss.png
  src/develop/ui/screen-templates-create/images/forge-6-ss.png
  src/develop/ui/screen-templates-create/images/forge-7-ss.png
  src/develop/ui/screen-templates-create/images/forge-8-ss.png
  src/develop/ui/screen-templates-create/images/forge-9-ss.png
  src/develop/ui/screen-templates-create/intro.md
  src/develop/ui/table/intro.md
  src/ref/lang/auto/Class.Table Records Widget.begin.md
  src/ref/lang/auto/Class.Table Records Widget.end.md
  src/ref/lang/auto/images/tablerecords-1-ss.png
  src/ref/lang/auto/images/tablerecords-10-ss.png
  src/ref/lang/auto/images/tablerecords-2-ss.png
  src/ref/lang/auto/images/tablerecords-3-ss.png
  src/ref/lang/auto/images/tablerecords-4-ss.png
  src/ref/lang/auto/images/tablerecords-5-ss.png
  src/ref/lang/auto/images/tablerecords-6-ss.png
  src/ref/lang/auto/images/tablerecords-7-ss.png
  src/ref/lang/auto/images/tablerecords-8-ss.png
  src/ref/lang/auto/images/tablerecords-9-ss.png
  toc.yml
Labels: cla:yes
