Repository OutSystems/docs-product, pull requests merged in 2021-05, with the labels that each got.

#162 Update mobile-app-update-scenarios.md
  src/deliver-mobile/mobile-app-update-scenarios.md
  src/extensibility-and-integration/mobile-plugins/ssl-pinning/intro.md
Labels: cla:yes, type/improvement

#124 Update known issue + change in extensibility configurations for PS 11…
  src/deliver-mobile/distribute-pwa/advanced.md
  src/deliver-mobile/distribute-pwa/troubleshooting-know-issues.md
Labels: cla:yes, status/waiting_for_release

#171 Fixed minor typos (Firebase plugin docs)
  src/extensibility-and-integration/mobile-plugins/firebase/intro.md
Labels: cla:yes

#153 Log Message - Message input limited to 2000 chars
  src/ref/apis/auto/system-actions.md
Labels: cla:yes, type/improvement

#180 Update use-external-lib.md
  src/extensibility-and-integration/javascript/mobile/use-external-lib.md
Labels: cla:yes

#176 Warning for on-premises
  src/managing-the-applications-lifecycle/secure-the-applications/apply-content-security-policy.md
Labels: cla:yes

#170 Internal communication clarification
  src/managing-the-applications-lifecycle/deploy-applications/zones/reference.md
Labels: cla:yes

#169 Change Widget name from "Content" to "Text"
  src/develop/ui/reuse/block-create-reuse.md
Labels: cla:yes

#167 Copyediting of the Multilingual docs
  src/develop/ui/multilingual-tp/intro.md
  src/develop/ui/multilingual-tp/translate-your-app.md
  src/develop/ui/multilingual-tp/translation-editor.md
  src/develop/ui/multilingual-tp/translation-management.md
  src/develop/ui/multilingual-tp/troubleshooting-known-issues.md
Labels: cla:yes, type/improvement

#179 Explain current language scope/duration
  src/develop/ui/multilingual/intro.md
Labels: cla:yes, type/improvement

#184 Revert "Explain current language scope/duration"
  src/develop/ui/multilingual/intro.md
Labels: cla:yes
