Repository OutSystems/docs-product, pull requests merged in 2021-01, with the labels that each got.

#144 Update set-up-platform.md
  src/setup/azure/set-up-platform.md
Labels: cla:no, cla:yes

#145 Fixed Configuration Tool command line reference for installing system components
  src/setup/unattended-install/config-tool-ref.md
Labels: cla:yes, status/feedback_wanted, type/improvement

#142 Adding gap: default values
  src/managing-the-applications-lifecycle/secure-the-applications/apply-content-security-policy.md
Labels: cla:yes, type/improvement

#146 SSL Pinning from Forge to docs in Markdown
  src/extensibility-and-integration/mobile-plugins/ssl-pinning/images/sslplugin-1-ss.png
  src/extensibility-and-integration/mobile-plugins/ssl-pinning/images/sslplugin-2-ss.png
  src/extensibility-and-integration/mobile-plugins/ssl-pinning/intro.md
  toc.yml
Labels: cla:yes, type/new_content
