Repository OutSystems/docs-product, pull requests merged in 2023-05, with the labels that each got.

#328 Update light-process.md
  src/develop/processes/light-process.md
Labels: cla:yes

#331 Update apply-content-security-policy.md
  src/managing-the-applications-lifecycle/secure-the-applications/apply-content-security-policy.md
Labels: cla:no

#323 Update system-requirements.md
  src/setup-maintain/setup/system-requirements.md
Labels: cla:yes

#337 Update broken link
  src/develop/ui/accelerators/intro.md
Labels: cla:yes

#332 RDV-577 link reviewing sast results
  src/ref/apis/lifetime-deployment/examples/api-request-code.md
Labels: cla:yes

#310 Fix events description
  src/ref/ui-patterns/mobile/carousel-mobile.md
Labels: cla:yes

#330 Added an example image from customer feedback
  src/extensibility-and-integration/integration-builder/connectors/images/connection-ib.png
  src/extensibility-and-integration/integration-builder/connectors/integration-ms-sharepoint.md
Labels: cla:yes

#335 Update server-hsconf-ref.md
  src/setup-maintain/setup/unattended-install/server-hsconf-ref.md
Labels: status/waiting_for_release, cla:yes

#329 Update limit-records-sql.md
  src/managing-the-applications-lifecycle/manage-tech-debt/code-patterns/images/limit-rows-sql-diag.png
  src/managing-the-applications-lifecycle/manage-tech-debt/code-patterns/images/limit-rows-sql.png
  src/managing-the-applications-lifecycle/manage-tech-debt/code-patterns/limit-records-sql.md
Labels: cla:yes

#341 Update manage-troubleshoot.md
  src/setup-maintain/setup/cache-invalidation/manage-troubleshoot.md
Labels: cla:yes

#336 Add a hyperlink for variables.
  src/develop/ui/patterns/web/controls/buttongroup.md
Labels: cla:yes
